### ISSUE TITLE
how to generate the file.xslt document ? code by myself or by the tools provided by iap

### ISSUE THREAD

**Issue by tantairs** [IBM-i2/Analyze#17]
hi, 
     I have generated the schema file by the requirement, and transformed excel file(the test source data) to the xml file that suitble for the iap. then i will revoke the interface of iap and insert the capable xml file into the Analysis Repository using the example (da-arload-filesystem-example), however, i don't know how to generate the xslt file compatible for my project(such as the dataToIap.xslt in the example). so i want to know, wheather it is generate by the tools provided by iap or edit it myself.  can you show me how to do it?
thanks.

**Comment by boalesth** [comment]
Hi Tantairs,

XSLT is just one of the many ways to transform incoming data into the correct format for ingestion. If you have already transformed your data and it is in a valid format, then there is no need to use an XSLT.

If you still want to use an XSLT, use the XSD files (that were created when you generated the mapping files) to create the transforms using a third party tool.

Thanks 

Esther
