### ISSUE TITLE
insert xml data into the iap

### ISSUE THREAD

**Issue by tantairs** [IBM-i2/Analyze#18]
hi boalesth,
     Following the above problem, i have conveyed the source data into the xml data imitating the code in the da-example-common  project (using the JAXB), however, i find that the data load method in the example using the -load parameter needs two parameters (one is the xml data that i have , another is the xslt file just like dataToiap.xslt ) to work , you telled me if have conveyed the data then i don't need the xslt file. but the load data method must need these two parameters. so i failded to insert the data into the iap. i get confused about it. (i have used the newest sdk and my iap version also the newest) .
[error: Failed Resource Type: [file] from the source class [XmlDataLoader] with additional context :Failed to load xml data ;
createNewException]
ps : it stands my formated xml fail ?
 
     another problem is that  my data is big about 300g , and each file is 2g, i am find the jvm out of the memory. so if i want to import a big data file, must i insert by several times? 
                                                                                                                                     thanks very much

**Comment by boalesth** [comment]
Hi Tantairs,
Firstly, you can set the xslt parameter to load an identity transform which will not transform your data: 

```
<?xml version="1.0" ?>
<xsl:stylesheet version="1.0"
   xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

   <!-- IdentityTransform -->
   <xsl:template match="/ | @* | node()">
         <xsl:copy>
               <xsl:apply-templates select="@* | node()" />
         </xsl:copy>
   </xsl:template>

</xsl:stylesheet>
```
For the second issue, I'm not sure how you are performing the import (or if your problem is the result of a search), but that is a lot of data! I'd consider loading that into a different system such as the operational warehouse provided with IBM i2 Enterprise Insight Analysis and querying the data from that location.

If you are certain that the data is suitable for ingestion, either break the data set into smaller files before attempting the import, or allocate more memory to the JVM.

Thanks

Esther

**Comment by tantairs** [comment]
Hi boalesth,
      thank you for your reply, i have known the second issue , but for the first one, I did it following your xslt code, different error is got:(Failed Resource Type: [FILE] from the source class [XMLDataLoader] with additional context [[]]: Failed to load xml data. 
caused by: javex.xml.bind.UnmarshalException: unexpected element(uri: " ", local : "BaseInfoData").
expected element (--) as the follows:
![errorinfo](https://cloud.githubusercontent.com/assets/3755786/9902037/0f6c35cc-5c9e-11e5-9127-9e1964178fbb.PNG)

My formated xml file just like this;
![Uploading baseinfomation.PNG…]()
So,i really confused about the name of the xml element or root xml name that how to correspond to the XSD file that i generate by the command build -t generateMappingJar -x -----   -o --------
I use the JABX to convey the data to xml data, i named my xml element or attribute or root name by myselt . is it the mistake that i make ? ( when i named the xml name, what attention i need to pay ?)
thanks

**Comment by boalesth** [comment]
Hi Tantairs,

Not a problem.

The first thing I'd suggest is to use the xsd files that were created when you created your mapping jar to validate your xml file. You could also use these to generate an xml sample file that will provide you with the structure that the platform expects. Once you have that, you can then create an xslt that will transform your data into this format or alter your data creation code to use this format in the first place.

Thanks

Esther

**Comment by boalesth** [comment]
Hi again Tantairs,

Here's a sample to help get you started:

```
<QueryResult xmlns:ns4="http://www.i2group.com/Schemas/2011-03-03/ModelSchemaExtension" xmlns:ns3="http://www.i2group.com/Schemas/2011-03-03/ModelSchema" xmlns:ns2="http://www.i2group.com/Schemas/2013-10-03/ModelData/Provenance">
	<PersontoPersons>
		<PersontoPerson>
			<Cards>
				<Card>
					<CardId>1</CardId>
					<ns2:CardProvenance>
						<RetrievalBlocks/>
						<OriginId Version="1" Type="Ibase_IAP_Production">
							<Key>
								<String>TOP1</String>
							</Key>
						</OriginId>
					</ns2:CardProvenance>
					<PersontoPerson_Relationship>Friends</PersontoPerson_Relationship>
				</Card>
			</Cards>
			<ItemId>TOP1</ItemId>
			<ItemVersion>0</ItemVersion>
			<LinkFromEndId>PER2</LinkFromEndId>
			<LinkToEndId>PER1</LinkToEndId>
			<LinkDirection>WITH</LinkDirection>
			<LinkStrength>Confirmed</LinkStrength>
			<SecurityTagIds>
				<SecurityTagId>d3cdf9a0-1164-11e3-8ffd-0800200a6789</SecurityTagId>
			</SecurityTagIds>
		</PersontoPerson>
	</PersontoPersons>
	<Vehicles>
		<Vehicle>
			<Cards>
				<Card>
					<CardId>1</CardId>
					<ns2:CardProvenance>
						<RetrievalBlocks/>
						<OriginId Version="1" Type="Ibase_IAP_Production">
							<Key>
								<String>VEH1</String>
							</Key>
						</OriginId>
					</ns2:CardProvenance>
					<Vehicle_VIN>2212AEG</Vehicle_VIN>
					<Vehicle_Make>Ford</Vehicle_Make>
					<Vehicle_Model>Troubador</Vehicle_Model>
				</Card>
			</Cards>
			<ItemId>VEH1</ItemId>
			<ItemVersion>0</ItemVersion>
			<SecurityTagIds>
				<SecurityTagId>d3cdf9a0-1164-11e3-8ffd-0800200a678a</SecurityTagId>
			</SecurityTagIds>
		</Vehicle>
	</Vehicles>
	<Addresss>
		<Address>
			<Cards>
				<Card>
					<CardId>1</CardId>
					<ns2:CardProvenance>
						<RetrievalBlocks/>
						<OriginId Version="1" Type="Ibase_IAP_Production">
							<Key>
								<String>ADD1</String>
							</Key>
						</OriginId>
					</ns2:CardProvenance>
					<Address_Address>23 Ramsey Hollow</Address_Address>
				</Card>
			</Cards>
			<ItemId>ADD1</ItemId>
			<ItemVersion>0</ItemVersion>
			<SecurityTagIds>
				<SecurityTagId>d3cdf9a0-1164-11e3-8ffd-0800200a678a</SecurityTagId>
			</SecurityTagIds>
		</Address>
	</Addresss>
	<Persons>
		<Person>
			<Cards>
				<Card>
					<CardId>1</CardId>
					<ns2:CardProvenance>
						<RetrievalBlocks/>
						<OriginId Version="1" Type="Ibase_IAP_Production">
							<Key>
								<String>PER1</String>
							</Key>
						</OriginId>
					</ns2:CardProvenance>
					<Person_FullName>Keon Bramley</Person_FullName>
					<Person_LastName>Bramley</Person_LastName>
					<Person_FirstName>Keon</Person_FirstName>
				</Card>
			</Cards>
			<ItemId>PER1</ItemId>
			<ItemVersion>0</ItemVersion>
			<SecurityTagIds>
				<SecurityTagId>d3cdf9a0-1164-11e3-8ffd-0800200a678a</SecurityTagId>
			</SecurityTagIds>
		</Person>
		<Person>
			<Cards>
				<Card>
					<CardId>1</CardId>
					<ns2:CardProvenance>
						<RetrievalBlocks/>
						<OriginId Version="1" Type="Ibase_IAP_Production">
							<Key>
								<String>PER2</String>
							</Key>
						</OriginId>
					</ns2:CardProvenance>
					<Person_FullName>Antonio Marcos</Person_FullName>
					<Person_LastName>Marcos</Person_LastName>
					<Person_FirstName>Antonio</Person_FirstName>
				</Card>
			</Cards>
			<ItemId>PER2</ItemId>
			<ItemVersion>0</ItemVersion>
			<SecurityTagIds>
				<SecurityTagId>d3cdf9a0-1164-11e3-8ffd-0800200a678a</SecurityTagId>
			</SecurityTagIds>
		</Person>
	</Persons>
	<VehicletoPersons>
		<VehicletoPerson>
			<Cards>
				<Card>
					<CardId>1</CardId>
					<ns2:CardProvenance>
						<RetrievalBlocks/>
						<OriginId Version="1" Type="Ibase_IAP_Production">
							<Key>
								<String>EHI1</String>
							</Key>
						</OriginId>
					</ns2:CardProvenance>
				</Card>
			</Cards>
			<ItemId>EHI1</ItemId>
			<ItemVersion>0</ItemVersion>
			<LinkFromEndId>VEH1</LinkFromEndId>
			<LinkToEndId>PER1</LinkToEndId>
			<LinkDirection>WITH</LinkDirection>
			<LinkStrength>Confirmed</LinkStrength>
			<SecurityTagIds>
				<SecurityTagId>d3cdf9a0-1164-11e3-8ffd-0800200a678a</SecurityTagId>
			</SecurityTagIds>
		</VehicletoPerson>
	</VehicletoPersons>
	<PersontoAddresss>
		<PersontoAddress>
			<Cards>
				<Card>
					<CardId>1</CardId>
					<ns2:CardProvenance>
						<RetrievalBlocks/>
						<OriginId Version="1" Type="Ibase_IAP_Production">
							<Key>
								<String>ERS1</String>
							</Key>
						</OriginId>
					</ns2:CardProvenance>
				</Card>
			</Cards>
			<ItemId>ERS1</ItemId>
			<ItemVersion>0</ItemVersion>
			<LinkFromEndId>PER1</LinkFromEndId>
			<LinkToEndId>ADD1</LinkToEndId>
			<LinkDirection>WITH</LinkDirection>
			<LinkStrength>Confirmed</LinkStrength>
			<SecurityTagIds>
				<SecurityTagId>d3cdf9a0-1164-11e3-8ffd-0800200a678a</SecurityTagId>
			</SecurityTagIds>
		</PersontoAddress>
	</PersontoAddresss>
</QueryResult>
``` 

Obviously you'll have to modify this to match your schema... but hopefully it helps!

Thanks

Esther

**Comment by tantairs** [comment]
thank you, i will check it tomorrow.

**Comment by tantairs** [comment]
hi boalesth,
   i have convey the four schema.xsd file provided by iap into the xml formation using the third tools. and add some context. (the first time i give you the xml sample is incorrect. because i generate not by the schema.xsd by iap). when i run in the da-aload-filesystem-example project (the xslt file i use the one you give me to keep the xml file still). i run to some problem. i have some chinese character in my xml then i gives me the error that not much. then i change the chinese my code runs no error. but no data is inserted into the iap. whether my schema.xsd include some chinese characters make the mistake. by the way, my version of my i2 is chinese. when i generate the schema file, the chinese characters are some hexadecimal numbers. does it make the effects? thanks very much.

**Comment by boalesth** [comment]
Hi Tantairs,

Can you post:
- a fragment of your xml
- the error message you are getting

Can you also confirm you are using the identity transform posted above?

Thanks

Esther

**Comment by tantairs** [comment]
hi boalesth，
    I have gone back home, i will send these info later, thanks for your help.

**Comment by tantairs** [comment]
hi boalesth，
      I have solved the problem of input XML data, thanks for your help again. however, I still have some questions when faced with requirements.  one is that When i defined a association between two phones,
how can i define the direction of the Link. it may have a receive or send direction in a phone. ( I know the data-load example have a xslt temple which has a statement that <LinkDirection>NONE</LinkDirection> but i don't know what's the value i need to set in the place of NONE to meet my needs. )  thanks.

**Comment by boalesth** [comment]
Hi Tanairs,

The sample above has link direction set to WITH... which will set the link direction in the way you want it to:

```
            <LinkDirection>WITH</LinkDirection>
```
Note: This sets the direction to  LinkFromEnd ----> LinkToEnd 

The full list of constants can also be found in the javadoc (https://github.com/IBM-i2/Analyze/tree/master/developer-essentials/SDK/sdk-projects/master/javadoc)

AGAINST
The link direction does not match the "from-to" direction.
BOTH
The link is bidirectional.
NONE
The link has no direction.
WITH
The link direction matches the "from-to" direction.
Thanks

Esther
