### ISSUE TITLE
law-enforcement-schema.jar does not generate correctly

### ISSUE THREAD

**Issue by Joai2** [IBM-i2/Analyze#19]
I am developing the DLD example in IAP 3.0.9 but when i run the command:

da-setup.py -t generate-mapping-jar -x law-enforcement-schema.xml -o law-enforcement-schema.jar

The created jar is not showing the name of the entitys, links, propertys nor property groups, instead it show EntityX, LinkX, PropertyX, PropertyGroupX (the X changes for a different number for all elements).

How can i create the .jar with the real names?

Thank you.

**Comment by boalesth** [comment]
Hi Joai,

The XSDs that are created within the jar should have the correct names embedded within them. Can you open those and check?

Thanks

Esther

**Comment by Joai2** [comment]
Hi Esther

I checked the XSDs and the schema4.xsd have the name correctly but the .jar still the same, without the names.

Greetings

**Comment by boalesth** [comment]
Hi Joai,

That is by design.
The classes in the jar are internal, and named  'EntityX' etc to allow schemas to support entity types that use reserved words, punctuation, and foreign characters. The xml that you need to create is xml that complies with schema4.xsd.

Thanks

Esther

**Comment by Joai2** [comment]
Hello boalesth!

Sorry for the late comment.

How can i create a xml that complies with schema4.xsd?

**Comment by johngid** [comment]
Is there a way of mapping from the schema4.xsd to the actual jar?, ie a way to know that Entity12 is Person.
