### ISSUE TITLE
Get Context example

### ISSUE THREAD

**Issue by Joai2** [IBM-i2/Analyze#20]
Hello

Do you have an example where i can develop a DAOD using Get Context to retrieve data?

Thanks

**Comment by boalesth** [comment]
Hi Joai,

All the available examples are posted here. 

It might be worth taking a look at the [Acxiom](https://github.com/IBM-i2/Data-Acquisition-Accelerators/blob/master/Data-Acquisition-Accelerators/Acxiom_Accelerator/Readme.md) example (specifically the ```AcxiomExternalDataItemRetriever``` class), as this uses a custom UI to display the results of calls to ```IExternalDataSubsetLocator``` and the ```IExternalDataItemRetriever``` APIs. 

Alternatively, if you would like to use the standard portal UI, you will need to have a class that implements the  ```IExternalDataAdapter```  and the ```IExternalDataItemRetriever``` API calls that you would like to use.

More Information:
Show Context  (getContext)  wire up

To help with ExternalDataRetrievalService calls,  where you are accessing the same data store as your search data etc is coming from, we have the following property 

```
# Whether or not an External Data Retrieval Service retrieval block is automatically created
# as part of the Subset Exploration Service ingestion process.
ExternalDataCreateStandardEDRSRetrievalBlock=true
```

Setting this to true means that when you get data via the ```SubsetExplorationService``` we will not only create you a retrieval block for that but also one that will automatically allow the item to be used as a seed for getContext and getItems too on the ExternalDataRetrievalService. This property is set in our ```ApolloServerSettingsDaodMandatory.properties``` file

What a lot of people do is have an implementing class that implements both ```IExternalDataAdapter``` and ```IExternalDataItemRetriever``` the first of these gives Search,  Full Text Search, Dumbbell Search via the ```ExternalDataSubsetExplorationService```, and the second gives getContext and getItems via the ```ExternalDataRetirevalService```.

A decision was made that within the native portal UI you could only either use Expand within an already retrieved subset or getContext against the source data store not both at the same time.

If you want to do anything serious with expand or getcontext though, you will need to use Analyst's Notebook Premium for the visualization as the Portal Viewer has no layout commands.

The data source also needs to be set up correctly in the topology file to support getContext:

```<iap-data-source id="MyId" ar="false">
            <DataSource EdrsPresent="true" ScsPresent="true" SesPresent="true" ScsBrowseSupported="true" ScsSearchSupported="true" ScsNetworkSearchSupported="true" ScsDumbbellSearchSupported="true" ScsFilteredSearchSupported="true" EdrsGetContextSupported="true" EdrsGetLatestItemsSupported="true" Id="" Version="0">
                <Shape>DAOD</Shape>
                <Name>MyDAConnector</Name>
            </DataSource>
        </iap-data-source>```

**Note:** ```EDRSGetLatestItemsSupported``` is set to true as some of the Analyst's Notebook Premium functionality calls this.

Your getContext code will therefore need to be the implementation of the getContext method on ```IExternalDataItemRetriever```.

You will also need to implement getLatestItems on this interface to get full functionality.
Thanks

Esther

**Comment by Joai2** [comment]
It worked! Thank you boalesth!
