### ISSUE TITLE
DAOD practical example - for iBridge migration

### ISSUE THREAD

**Issue by ViliusB** [IBM-i2/Analyze#25]
Dear community, maybe someone has an example/sample to share from real working default IAP schema DAOD connector?

lest say, that one table has persons (ID and person name, family name) another has Vehicles (number plate, manufacture date), and 3rd - links between (PersonID, Vehiclenumber plate).

Such example, with clear working search by number plate, and expand from Number plate, would be a great example how to make it work. And it could relate very clearly how to go from iBridge to IAP DAOD.

As now barrier for new specialists is very high, when examples are very specialised, and missing real world samples, of sources implementation.

From what I was talking in User Conference in DC this September, there are POCs being run where such connectors are demonstrated, so they should exist, right? :)

I hope it could come as Christmas Gift for us, Santa - would you help?

vilius

**Comment by Bodstrup** [comment]
Too late for Santa - but have you solved the issue ?

You appear to raise two questions, correct me if I am wrong:

1. Can we have a database with a number of tables, defining say Individuals, License Plates, Vehicles, Addresses etc  - then link them, so you can get from a license plate to a vehicle and it's owner ?

The answer is clearly YES; this is what the i2 products (iBase, i2 Analyze, Analyst's Notebook) was made for.

All you need is a schema - the default schemas supplied with either of the above products can handle what you need, perhaps with the license plate added as an entity.

2. iBridge: Which database do you wish to connect to ? There is a standard offering connecting i2 Analyze with iBase, if you need to connect to another database, we probably need to develop a connector.

Regards

Michael/IBM i2

**Comment by ViliusB** [comment]
Santa is always on time, if not for last year, this year is still open :)

I rephrase - I have a simple ibridge integration to Oracle SQL of 3 tables (person, vehicle, and when particular person in particular vehicle crossed border).

I want to move it to DAOD, and lack of a proper example, how to do that. I know (I talked with IBM technical people in i2 User Forum in September) that simple integrations are not too difficult to make, but there is no example in SDK.

Thus, please provide an example of simple 3 table (two tables - objects, one table - links between these objects) DAOD integration for default Analyze data schema. This would serve as a great practise for all out there existing needed migrations from iBridge to DAOD.

Is this clear?

Vilius/ waiting for Santa...

**Comment by Bodstrup** [comment]
I have forwarded your response to a contact in the i2 Lab, will update you when I get a reply.

Unfortunately I have no experience writing DAOD Connectors or configuring any of them except  the one for iBase.
