### ISSUE TITLE
What is the best way to hot deploy during development?

### ISSUE THREAD

**Issue by au-arena** [IBM-i2/Analyze#26]
Hi,

after each code modfication I want to test the result in IAP. The only means I have found so far is to do:

build -t deploy

which is quite long (1 min) and not convenient.

Is there a better way for code modifications to be taken into account ?

Thanks

**Comment by AamirShipton** [comment]
During development you should really be using Eclipse both for modifying and running your code. If you look at the instructions for the da-subset-filesystem-example project you will notice that it tells you how to add your Liberty server to Eclipse' 'Servers' view. Once this is set up correctly you can use the 'Publish' feature on that Eclipse server to push changes that you have made to your project into Liberty's deployed WAR file.

The Eclipse server can also be run in debug mode allowing you to step through the code one line at a time and use breakpoints to choose where to stop. You can read more about this in Eclipse' documentation.

Note: Publishing the Eclipse server only publishes changes to your projects' files. Other changes to the i2 Analyze toolkit will still require that you run deploy as you described.

**Comment by au-arena** [comment]
Hi,

while trying this out, I encountered this problem when clicking on the datasource icon on the left panel:

----------------------------------------------------------------
Le référentiel n'a pas réussi à répondre. Contactez votre administrateur système.i2.Apollo.Common.Exceptions.ServerNotFoundException
Server could not be found. 

System.ServiceModel.CommunicationException
[HttpWebRequest_WebException_RemoteServer]
Arguments : NotFound
Les chaînes de ressource de débogage ne sont pas disponibles. Souvent la clé et les arguments fournissent suffisamment d'informations pour diagnostiquer le problème. Consultez http://go.microsoft.com/fwlink/?linkid=106663&Version=5.1.41105.0&File=System.Windows.dll&Key=HttpWebRequest_WebException_RemoteServer    à System.ServiceModel.AsyncResult.End[TAsyncResult](IAsyncResult result)
   à System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   à System.ServiceModel.ClientBase`1.ChannelBase`1.EndInvoke(String methodName, Object[] args, IAsyncResult result)
   à i2.Apollo.Services.Internal.ExternalDataSubsetExploration.AutoGen.ExternalDataSubsetExplorationServiceClient.ExternalDataSubsetExplorationServiceClientChannel.EndSearch(IAsyncResult result)
   à i2.Apollo.Services.Internal.ExternalDataSubsetExploration.AutoGen.ExternalDataSubsetExplorationServiceClient.i2.Apollo.Services.Internal.ExternalDataSubsetExploration.AutoGen.ExternalDataSubsetExplorationService.EndSearch(IAsyncResult result)
   à i2.Apollo.Services.Internal.ExternalDataSubsetExploration.AutoGen.ExternalDataSubsetExplorationServiceClient.i2.Apollo.Services.Internal.ExternalDataSubsetExplorationService.IExternalDataSubsetExplorationServiceInternals.EndSearch(IAsyncResult asyncResult)
   à i2.Apollo.Services.ExternalDataSubsetExplorationService.ExternalDataSubsetExplorationServiceFacade.CompleteAndMarshalSearch(IExternalDataSubsetExplorationServiceInternals client, IAsyncResult resultToken)
   à i2.Apollo.Services.AsynchronousCallCompleter`2.GetResponse(IAsyncResult asyncResult, TResult& successResult, Exception& failureException)

System.Net.WebException
[HttpWebRequest_WebException_RemoteServer]
Arguments : NotFound
Les chaînes de ressource de débogage ne sont pas disponibles. Souvent la clé et les arguments fournissent suffisamment d'informations pour diagnostiquer le problème. Consultez http://go.microsoft.com/fwlink/?linkid=106663&Version=5.1.41105.0&File=System.Windows.dll&Key=HttpWebRequest_WebException_RemoteServer    à System.Net.Browser.AsyncHelper.BeginOnUI(SendOrPostCallback beginMethod, Object state)
   à System.Net.Browser.BrowserHttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   à System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelAsyncRequest.CompleteGetResponse(IAsyncResult result)

System.Net.WebException
[HttpWebRequest_WebException_RemoteServer]
Arguments : NotFound
Les chaînes de ressource de débogage ne sont pas disponibles. Souvent la clé et les arguments fournissent suffisamment d'informations pour diagnostiquer le problème. Consultez http://go.microsoft.com/fwlink/?linkid=106663&Version=5.1.41105.0&File=System.Windows.dll&Key=HttpWebRequest_WebException_RemoteServer    à System.Net.Browser.BrowserHttpWebRequest.InternalEndGetResponse(IAsyncResult asyncResult)
   à System.Net.Browser.BrowserHttpWebRequest.<>c__DisplayClassa.<EndGetResponse>b__9(Object sendState)
   à System.Net.Browser.AsyncHelper.<>c__DisplayClass4.<BeginOnUI>b__1(Object sendState)

----------------------------------------------------------------

It seems that the datasource can't be reached, but I can't figure out the problem or where to look for. Let me know if you need more specific informations.

Thanks

**Comment by au-arena** [comment]
solved, I have reinstalled the SDK + workspace

**Comment by au-arena** [comment]
Hi,

I actually have some problem to follow the instruction from:

https://github.com/IBM-i2/Analyze/blob/master/documentation/developer_essentials_example_daod.md

from 
> "The commands so far deployed the example project application from the toolkit. (...)" 

up to the end.

The consequence is that modification are not taken into account.

Thanks

**Comment by au-arena** [comment]
the same error reappeared when click on the datasource icon:

----


Le référentiel n'a pas réussi à répondre. Contactez votre administrateur système.i2.Apollo.Common.Exceptions.ServerNotFoundException
Server could not be found. 

System.ServiceModel.CommunicationException
[HttpWebRequest_WebException_RemoteServer]
Arguments : NotFound
Les chaînes de ressource de débogage ne sont pas disponibles. Souvent la clé et les arguments fournissent suffisamment d'informations pour diagnostiquer le problème. Consultez http://go.microsoft.com/fwlink/?linkid=106663&Version=5.1.41105.0&File=System.Windows.dll&Key=HttpWebRequest_WebException_RemoteServer    à System.ServiceModel.AsyncResult.End[TAsyncResult](IAsyncResult result)
   à System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   à System.ServiceModel.ClientBase`1.ChannelBase`1.EndInvoke(String methodName, Object[] args, IAsyncResult result)
   à i2.Apollo.Services.Internal.ExternalDataSubsetExploration.AutoGen.ExternalDataSubsetExplorationServiceClient.ExternalDataSubsetExplorationServiceClientChannel.EndSearch(IAsyncResult result)
   à i2.Apollo.Services.Internal.ExternalDataSubsetExploration.AutoGen.ExternalDataSubsetExplorationServiceClient.i2.Apollo.Services.Internal.ExternalDataSubsetExploration.AutoGen.ExternalDataSubsetExplorationService.EndSearch(IAsyncResult result)
   à i2.Apollo.Services.Internal.ExternalDataSubsetExploration.AutoGen.ExternalDataSubsetExplorationServiceClient.i2.Apollo.Services.Internal.ExternalDataSubsetExplorationService.IExternalDataSubsetExplorationServiceInternals.EndSearch(IAsyncResult asyncResult)
   à i2.Apollo.Services.ExternalDataSubsetExplorationService.ExternalDataSubsetExplorationServiceFacade.CompleteAndMarshalSearch(IExternalDataSubsetExplorationServiceInternals client, IAsyncResult resultToken)
   à i2.Apollo.Services.AsynchronousCallCompleter`2.GetResponse(IAsyncResult asyncResult, TResult& successResult, Exception& failureException)

System.Net.WebException
[HttpWebRequest_WebException_RemoteServer]
Arguments : NotFound
Les chaînes de ressource de débogage ne sont pas disponibles. Souvent la clé et les arguments fournissent suffisamment d'informations pour diagnostiquer le problème. Consultez http://go.microsoft.com/fwlink/?linkid=106663&Version=5.1.41105.0&File=System.Windows.dll&Key=HttpWebRequest_WebException_RemoteServer    à System.Net.Browser.AsyncHelper.BeginOnUI(SendOrPostCallback beginMethod, Object state)
   à System.Net.Browser.BrowserHttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   à System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelAsyncRequest.CompleteGetResponse(IAsyncResult result)

System.Net.WebException
[HttpWebRequest_WebException_RemoteServer]
Arguments : NotFound
Les chaînes de ressource de débogage ne sont pas disponibles. Souvent la clé et les arguments fournissent suffisamment d'informations pour diagnostiquer le problème. Consultez http://go.microsoft.com/fwlink/?linkid=106663&Version=5.1.41105.0&File=System.Windows.dll&Key=HttpWebRequest_WebException_RemoteServer    à System.Net.Browser.BrowserHttpWebRequest.InternalEndGetResponse(IAsyncResult asyncResult)
   à System.Net.Browser.BrowserHttpWebRequest.<>c__DisplayClassa.<EndGetResponse>b__9(Object sendState)
   à System.Net.Browser.AsyncHelper.<>c__DisplayClass4.<BeginOnUI>b__1(Object sendState)
