### ISSUE TITLE
I2 Analyze reporting

### ISSUE THREAD

**Issue by DenysUA** [IBM-i2/Analyze#28]
Hello!

I have one question.
Have can I retrieve the information from I2 Analyze repository (DB2 database) to build the reports in IBM Cognos BI?
Or may be there is another functionality to reports (like it was in iBase)?

Thank you in advance.

**Comment by TonyJon** [comment]
Hi Denys

Items are stored in the i2 Analyze repository (AR) as compressed XML blobs. 
Access to the items/data that those XML blobs contain is only supported through our our search service which  makes use of our Lucene Index and our internal data access code. 

Details of this search service and other services/API's that may be of use to you can be found in the Javadoc on GitHub [http://ibm-i2.github.io/Analyze/docs/overview-summary.html]

Alternatively there is the ability to export items to CSV or  print  from the results grid in the Portal.

You can also send items to i2 Analyst's Notebook Premium from the results grid in the Portal if you opened it from that application by using the  "Show Intelligence Portal" option and can then make use of the publishing functionality from there.
