### ISSUE TITLE
Can't find data1.xml in subset-filesystem-example

### ISSUE THREAD

**Issue by FLepetit** [IBM-i2/Analyze#29]
Hi everyone,

After following each step of your documentation, I would like to edit the content of the data1.xml file. 

However after multiple searches I found some occurences for this file. I edited differently all of them to know which one is correct but search results in IAP did not change.

Thanks in advance,
Florian

**Comment by TonyJon** [comment]
Hi Florian

When you copy the Developer Essentials folders over the standard toolkit, data1.xml  is put in 
C:\IBM\i2analyze\SDK\sdk-projects\da-example-common\fragment\WEB-INF\classes

If you edit data1.xml in that folder (you can do this from Eclipse) and save it, you should see that your i2 Analyze server in Eclipse knows it needs to republish.

If you publish the change by right clicking on the server  and selecting that option,  and then start the server in Eclipse, you should be able to log in to the portal and see your changes when you search on the da-subset-filesystem-example data source.

I tried this by changing the first name of one of the people in that file.

If you do something more  interesting,  like adding completely new items into data1.xml, then they will only be seen in the Portal if they are matched  and translated by the  dataToI2analyze.xslt in to our  format.

Cheers

**Comment by FLepetit** [comment]
Thanks a lot TonyJon for your quick answer

Is there a DAOD example allowing to get connected to relationnal databases ?

**Comment by garywi** [comment]
Hi Florian
My team will be in touch via the IBM communication channels.
Regards
