### ISSUE TITLE
Error after in ELP format

### ISSUE THREAD

**Issue by johngid** [IBM-i2/Analyze#31]
Hello guys, I am currently working in an i2 Analyze DAOD connector. I am trying to use the fields in the schema, in particular the "RetrievalBlock" in order to know where the data came from.

I am attaching an input file, the output (transformed XML), and the XSLT. 

I get the following error:

`[com.i2group.apollo.common.toolkit.internal.ConsoleLogger] - (da-subset-db2-sample-database) - Failed Resource Type: [FILE] from the source class [XmlDataLoader] with additional context [[schema1.xsd, schema2.xsd, schema3.xsd, schema4.xsd]]: Failed to load XML data. - 'unexpected element (uri:"http://www.i2group.com/Schemas/2013-10-03/ModelData/Provenance", local:"RetrievalBlock"). Expected elements are <{}RetrievalBlock>' at line -1, column -1.`

But I can't seem to find out how to correct it. Please advise

[toSend.zip](https://github.com/IBM-i2/Analyze/files/180153/toSend.zip)

**Comment by TonyJon** [comment]
Hi Jon

Please see my reply to your earlier post.

[https://github.com/IBM-i2/Analyze/issues/30](url)

Hopefully this will help.
