### ISSUE TITLE
expand(...) method is never invoke from my IExternalDataAdapter implementation

### ISSUE THREAD

**Issue by jlvila** [IBM-i2/Analyze#32]
Dear,
I implement a DAOD connected to my search engine.
I had implemented: dumbbellSearch (it works fine), networkSearch (it works fine), fullTextSearch (Ok too), search(ok) BUT when i click expand ... application gave me some probably "cached" data ????? and never go trought my method (I use Java remote debug to know or not my methods are invoked)

My config :
Analyze 4.1.1
Topology.xml ==> 
    <i2-data-source id="daod3" ar="false">
        <DataSource EdrsPresent="false" ScsPresent="true"
            SesPresent="true" ScsBrowseSupported="true" ScsSearchSupported="true"
            ScsNetworkSearchSupported="true" ScsDumbbellSearchSupported="true"
            ScsFilteredSearchSupported="true" EdrsGetContextSupported="false"
            EdrsGetLatestItemsSupported="false" Id="" Version="0">
            <Shape>DAOD</Shape>
            <Name>SearchEngine</Name>
        </DataSource>
    </i2-data-source>

DAOD.propereties :
# Fri, 04 Mar 2016 08:12:13 +0000
# NLS_ENCODING=UTF-8
# NLS_MESSAGEFORMAT_ALL
### External Data Service Mandatory Configuration Options
# The full class name of the IExternalDataItemEditor to use
# IExternalDataItemEditor=

IExternalDataItemEditor=swordInsight.daod.graph.SearchItemEditor
IExternalDataItemEditor.modules=
# The full class name of the IExternalDataSubsetLocator to use

IExternalDataSubsetLocator=com.i2group.apollo.externaldata.CreatingSubsetLocator
IExternalDataSubsetLocator.modules=com.i2group.apollo.externaldata.CreatingSubsetLocatorModule
# The full class name of the IExternalDataAdapter to use

IExternalDataAdapter=swordInsight.daod.graph.SearchDataAdapterSubset
IExternalDataAdapter.modules=
# The full class name of the IExternalDataItemRetriever to use
# ExternalDataCreateStandardEDRSRetrievalBlock=true

IExternalDataItemRetriever=com.i2group.connector.daod.elp.simple.SimpleELPViewsDataAdapterSubset
# IExternalDataItemRetriever=swordInsight.daod.graph.SearchExternalDataRetriever
# The full class name of the IExternalDataDocumentSource to use

IExternalDataDocumentSource=swordInsight.daod.graph.SearchExternalDataDocumentSource
# If true then the XML that is passed to data acquisition is validated. This should be enabled while developing
# Data Access on Demand solutions, and turned off in production environments.
# Note: This validation only supports the multiple card format XML, and not the single card format.

ValidateXml=false
# The schema definitions that are used to validate the XML passed to data acquisition.
# By default, this is set to schema1.xsd,schema2.xsd,schema3.xsd,schema4.xsd

SchemaValidationXsdName=schema1.xsd,schema2.xsd,schema3.xsd,schema4.xsd

**Comment by johngid** [comment]
Hello, 

I am in no way an expert, however I have developed the "expand" capability. 

You see, in a DAOD connector the expand capability is called "show context", so in your topology file you need to set that to true. In my own connectors I also have the show latest items as true, but I'll be honest, I don't know if that affects the outcome. 

You will also note that on the context menu, instead of an expand, the option will say "show context" 

EdrsGetContextSupported="true"
EdrsGetLatestItemsSupported="true"

Regards 
JJ

**Comment by boalesth** [comment]
Firstly a huge thank you to John Jorge! A really good reply! 
As you say the `iap-data-source` element definition in the topology relate to this functionality:

`EdrsPresent="true"` 
`EdrsGetContextSupported="true"` 
`EdrsGetLatestItemsSupported="true"`

In addition to following these instructions, and refer to this information: 
[https://github.com/IBM-i2/Analyze/issues/20](get Context Example)

Thanks
Esther

**Comment by jlvila** [comment]
Sorry, but no,
The GetContext is in no way the same as expand fonction, my clues:
1) getContext is implied in edrs, expand not 
2) They are mutually exclusive, if I active getContext (erds), expand disappears
3) getContext must be implemented throw IExternalDataItemRetriever and expand throw IExternalDataAdapter 

As you can notice in my daod.properties, IExternalDataItemRetriever is commented.
I know this and I use it in another context. My question is focus on the case if i want to use **IExternalDataAdapter**  only implementing the corresponding method including "expand(...)".

After all, i try this combination erdsXXX="true" using the default simpleELPViewsDataAdapterSubset but from the item context menu, i have "Expand" with no relevant result (from already loaded items, i guess), in the graph view "Show context" is always grayed

**Comment by jlvila** [comment]
If a ask the question differently, how can i use expand function from my class implementing IExternalDataAdapter?

**Comment by boalesth** [comment]
Hi once again,

You are right.... getContext and expand are not the same thing (although they are closely related)....

One of the biggest differences between the two is that expand retrieves linked items from the subset of items that has already been retrieved, where as getContext returns links from the original data source. 

In order to use the expand function in the manner you describe, you would need to implement a custom UI.

Thanks

Esther

**Comment by jlvila** [comment]
Hi,
Ok, it is what I thought :-)
but just why expand(...) is defined inside IExternalDataAdapter without using it? the answer could be "by design"!
Jean-Louis
