### ISSUE TITLE
In ELP format is PropertyBags a required element?

### ISSUE THREAD

**Issue by johngid** [IBM-i2/Analyze#35]
In ELP format is PropertyBags a required element?

If so, does it have any children that are mandatory?

(Asking about ELP for version of IAP 3.0.5.1)

**Comment by TonyJon** [comment]
Hi

In the XML format  used for our data acquisition connectors PropertyBags is not a required element.

The definition for the specific XML that you need to create for your current schema can be found in the XSD files that are created as part of the generate-mapping-jar task.

If you look in schema4.xsd you can see the following:

      <xs:element name="_8_PropertyBags" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="PropertyBag" type="PropertyBag" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
