### ISSUE TITLE
getContext return xml issue?

### ISSUE THREAD

**Issue by tbozik** [IBM-i2/Analyze#37]
Hi all, 
I'm new in i2analyze daod development, so sorry for silly question.
I have a problem with implementation of the getContext function from the class that imeplements the IExternalDataItemRetrieverinterface and I was not able to find any solid example nor solution to my problem..

When I fetch the link between entities using fulltext search and visualize it, it work fine. But when I try to call getContext function for one end of the link the response xml (exactly the same as from the fulltext search = 2 entites, 1 link) contains 2 valid entities and 1 valid link but portal says: "No items found".

Is there any sample, how the getContext function should create the response correctly and how should be the xml formed for example for the default  law-enforcment-schema?

thx.

**Comment by boalesth** [comment]
Hi Tbozik,

All the examples that we document are  posted here... however I did answer this a while ago:

[https://github.com/IBM-i2/Analyze/issues/20](url)

Hopefully this helps, but please let me know if it doesn't

Esther

**Comment by tbozik** [comment]
Hi Esther,
 thanks for you quick response.
I have double checked the configuration and it seems to be not an issue. The getContext call is handled by my class and it returns a result. Unfortunatelly, the portal does not reflect my xml content and it gives "No items found" information box even when the response xml from my code contains valid data (no validation error on the server side) validated against schema.

Tomas

**Comment by boalesth** [comment]
Hi Tomas,

A slightly longer delay this time as I try to get more information from the team. Have you verified that the user that you are using has read permission on the items you are returning?

Thanks

Esther

**Comment by tbozik** [comment]
Hi Esther,
 it is the same user for both cases.

**Comment by boalesth** [comment]
Hi Tomas,

At this point I think taking a look at your files would be useful. Is that something you'd be happy to attach here?

Esther

**Comment by tbozik** [comment]
Hi Esther,
 thank you for your effort. Please see attached xml's.

[fulltextResult.xml.txt](https://github.com/IBM-i2/Analyze/files/719761/fulltextResult.xml.txt)
[getContextResult.xml.txt](https://github.com/IBM-i2/Analyze/files/719762/getContextResult.xml.txt)

**Comment by boalesth** [comment]
Thanks Tomas, I'll pass these on to the dev team and get a reply for you after the weekend... keep me posted if anything changes your side.

**Comment by TonyJon** [comment]
Hi Tomas

As the XML you generate  to return entities and links  is successfully doing so when your search returns these types and in that case they display in the UI for you  then I expect that your XML is OK and so are your access permissions for those returned items.

One thing that often catches people out with get context is that they do not fully populate the Collection of ContextResultMapping elements  as well as the XML Source in the return result.

In a simple example, if you select two entities in your UI you would receive two provenance groups in the provenanceGroups parameter and correspondingly you would have to return two ContextResulMapping elements. 

Each of these elements  link the incoming ProvenanceGroup  id  with the id's of the  items (entitys and links) that are being returned for each.  (Each has to include the original selected entity id  too).

It would be worth double checking that this has been correctly generated by your code, as in this instance,  the UI will only display entities and links that are described  in the ContextResultMapping collection.

Cheers

Tony

**Comment by tbozik** [comment]
Dear Tony,
 thanks for your response. the issue was, that I originally aded only source item id to the ContextResultMapping. When I added all item ids bound to the source item id to ContextResultMapping, everything started to work.

Closing now.
