### ISSUE TITLE
Analyze 4.1.3 deploying

### ISSUE THREAD

**Issue by RichGitHub1** [IBM-i2/Analyze#39]
I think I am misunderstanding "developer_essentials_deploying" steps for Analyze 4.1.3

https://github.com/IBM-i2/Analyze/blob/master/documentation/developer_essentials_deploying.md

I got stuck at step 8
8.- "Create a server in Eclipse that represents the awc application by repeating the steps above, and creating a server named awc."

I previously created a server named "i2analyze" so creating a new server with the same instance but named awc would create conflicts.

How do I create this new server named awc with no conflicts with server i2analyze created previously?

**Comment by boalesth** [comment]
Hi Rich,

You are correct, creating two servers in the same instance would cause conflicts. This is why the provided topology defines each sever in a separate instance. As long as you use the supplied files you should be fine.

Thanks

Esther

**Comment by hilljona** [comment]
Hi, Rich.

To complete Step 8, you have to change what you do in parts iv. _and_ v. of the previous step. That is, as well as changing the server name to "awc", you must also select "awc" from the **Liberty server** list. When you do that, you should be able to create the "awc" server in Eclipse successfully.

Cheers,

Jon.

**Comment by RichGitHub1** [comment]
Hello, Jon.

At the time to select awc from the Liberty server list, there is no "awc" I have to add new and name it awc manually, I suppose is the same.

Thank you.
