### ISSUE TITLE
Configuring the "user interface extension" example project support external website links

### ISSUE THREAD

**Issue by lawndale5** [IBM-i2/Analyze#42]
Had a question about "Configuring the "user interface extension" example project".
I see that it's paired with "two-phase data retrieval"  example project and was wondering if can make a external website appear?   Is it possible to have the tab link or submenu link open a external website for example www.ibm.com in the bottom body pane/frame or as a pop-up instead of the GitHub given hosted application project as it is registered with a data source id and external site wouldn't be.

**Comment by matthadf** [comment]
Hi lawndale5, 

Yes, you can make it so that an external site appears. You effectively end up with an iFrame that hosts the content.

The given hosted application has a data source id because it is used to query a data source.

Thanks,
Matt
