### ISSUE TITLE
Change the context of DAOD

### ISSUE THREAD

**Issue by johngid** [IBM-i2/Analyze#48]
When adding a DataSorce wit the command:

`build -pr onyx-da-subset-filesystem-example -t addDaodDataSource`

A datasource is added with a certain ID (that looks like a has), I was wondering if that can be customized to a more human readable string.

I am currently in a situation that will have a big number of DAODs, and for maintainabiliy reasons, I would liketo be able to identify them by reading the name.

I have found a couple of places where this id is being used (a datsource.properties file, the topology). When I deploy, and manually change these values, I have the behaviiour I want, however those are several manual changes each time I run the deploy commands.

Are there specific files that I should change? (The datasource,properties is an autogenerated file, but I can'find where it is gets its data from)

Regards
John

**Comment by TonyJon** [comment]
Hi John

Unfortunately the dsid properties file and its contents are procedurally generated as you have noticed.  It is built up from a number of different scripts and  property files.  

Are you  talking about the  TopologyId  (daod1 for example) or the dataSourceId  which is a GUID ( e47e586d-6ec6-4894-9b13-7d8c910588dd for example).

Cheers
