### ISSUE TITLE
Eclipse: Missing JARs in master-Project

### ISSUE THREAD

**Issue by quazee** [IBM-i2/Analyze#49]
Hi everybody,

I've successfully deployed the SDK following the brilliant guide provided here. But after importing the sample projects into Eclipse (Oxygen) building the "master"-project fails because of missing jars:

_Project 'master' is missing required library: 'build/toolkit/application/client/bin/apollo-client-4.1.6.0.jar'
Project 'master' is missing required library: 'build/toolkit/application/shared/lib/apollo-Core-3.1.17.0.jar'
Project 'master' is missing required library: 'build/toolkit/application/shared/lib/apollo-data-acquisition-delps-service-1.1.17.0.jar'
..._

And on it goes for 35 libraries. How do I fix this?

Best regards

Quazee

**Comment by TonyJon** [comment]
Hi Quazee

The fact that a core part of  how Developer essentials works is missing so many jar files makes me think that perhaps a step has been missed in the deployment  or perhaps something went wrong but it was not noticed.

Are you using Developer Essentials in a stand alone  i2 Analyze  deployment or an   EIA  i2 Analyze deployment? (You can tell the difference by what path you have to your toolkit, it will be ...\i2analyze\toolkit  or ...\i2EIA\toolkit).

When you followed the instructions in the  **Deploying IBM i2 Analyze Developer Essentials** document and ran **build -t deployExample** from this folder  ...\i2EIA\SDK\sdk-projects\master or this one ...\i2analyze\SDK\sdk-projects/master,  it should have created  a new  toolkit under master here  ...\SDK\sdk-projects\master\build\toolkit which is the one that you will use for Developer Essentials. 

Inside that toolkit there should be configuration/logs folder and that should contain  a log of the deployExample  command that you have run. (Logs are named  based on the command you run and the date and time).

Can you check please that the new toolkit and  the log file are there and see if there are any errors or warnings in the log file please.

Can you also check to see if the jar files that eclipse is complaining about are actually in the folder that it is trying to find them in ...\SDK\sdk-projects\master\build\toolkit\application\shared\lib . If they are not then part of the deployExample has failed but if they are then you may be missing  the TOOLKIT_ROOT definition in your Eclipse defined path variables list as is described in the **Configuring the "data load direct" example project** document for example.

Did you complete all of the steps detailed in Deploying IBM i2 Analyze Developer Essentials** document?

When you started the development version of the opal and onyx  servers from Eclipse (before adding the master  project to it, did they start up OK? 

Can you check the logs for  those  start operations (They are in the same folder as the deployExample log file mentioned above) please, to see if you have any warnings or errors.

I am assuming that you are using the  latest Developer Essentials **Developer Essentials for IBM i2 Analyze v4.1.6** and that you are using either the i2 Analyze 4.1.6 or the i2EIA 2.1.7 toolkit. Can you confirm that please?

Cheers

**Comment by TonyJon** [comment]
Hi again Quazee

I notice that you are using Eclipse Oxygen, we specify Eclipse Neon in our documentation. 

This may not be an issue but  I have not  tried with that version myself so I will put it on my VM just to be sure.

Cheers

**Comment by TonyJon** [comment]
HI Quazee

Eclipse Oxygen seems to work fine.

![image](https://user-images.githubusercontent.com/17141806/37097571-b36362b2-2213-11e8-9f72-95d9e52161dd.png)

**Comment by quazee** [comment]
Hi TonyJon,

thank you very much for your extensive answers. I'm afraid the problem has been sitting in front of the screen all along: I've inadvertently been using i2A 4.1.3 instead of 4.1.6. So, my bad, sorry and thank you once again for looking into this.

Cheers

Quazee
