### ISSUE TITLE
i2 EIA -Analyze

### ISSUE THREAD

**Issue by Shamimsbm** [IBM-i2/Analyze#51]
Hi,

I have installed and deploy i2 EIA on window 2012 server on a virtual machine. I followed this link 
https://www.ibm.com/support/knowledgecenter/SSXVXZ_2.2.0/com.ibm.i2.eia.install.doc/c_install_top.html
I have installed 
I2 EIA
Db2,
Http Server
i2 Analyst Notebook Premium
i2 iBase
i2 iBase intellishare 
Then followed deployment process as mention follows
https://www.ibm.com/support/knowledgecenter/SSXVXZ_2.2.0/com.ibm.i2.deploy.example.doc/deployment_toolkit_structure.html

I used "Deploying both the Analysis Repository and the Information Store " deployment type
https://www.ibm.com/support/knowledgecenter/SSXVXZ_2.2.0/com.ibm.i2.deploy.example.doc/t_deploy_ar_is.html

It has two option I selected Setting up the Opal and Onyx configuration ( https://www.ibm.com/support/knowledgecenter/SSXVXZ_2.2.0/com.ibm.i2.deploy.example.doc/setting_opal.html)

Note : I installed everything on local machine

Now when I came into connecting client section ( https://www.ibm.com/support/knowledgecenter/SSXVXZ_2.2.0/com.ibm.i2.deploy.example.doc/connecting_to_clients.html) I am facing some issue
In this section we have three things
1)  Connecting IBM i2 Analyst's Notebook Premium to IBM i2 Analyze ( https://www.ibm.com/support/knowledgecenter/SSXVXZ_2.2.0/com.ibm.i2.anb.admin.doc/connecting_to_anbpremium.html  )
           -- After opening notebook premium I have provided url ( http://localhost/opal ). Then it asked for login credential. I have provided Jenny/Jenny as it given in example. It throwing error that user doesn't have access to use i2 analyze

I followed the process as given in IBM documentation then how come this issue. How to fix it

2) Opening the web client to access information store ( https://www.ibm.com/support/knowledgecenter/SSXVXZ_2.2.0/com.ibm.i2.deploy.example.doc/opening_the_web_client.html )

I am providing  http://localhost/opal url on internet explorer( 11) but nothing happening, no message nothing.
How can I fix this ?

3) Opening the Intelligence Portal ( https://www.ibm.com/support/knowledgecenter/SSXVXZ_2.2.0/com.ibm.i2.deploy.example.doc/connect_to_the_intelligence_po.html )

I am  http://localhost/apollo  url through internet explorer. I have used Jerry/Jerry credential and it’s successfully connected to intelligence portal 

So I am facing issue on 
    Connecting IBM i2 Analyst's Notebook Premium to IBM i2 Analyze 
    Opening the web client to access information store

Please help me out.

Thanks,
Shamim

**Comment by matthadf** [comment]
Hi Shamim,

This is a forum for supporting issues with Developer Essentials and i2 Analyze. From your description, you are not using Developer Essentials. If you continue to have issues with the product, you should contact IBM Support.

In this instance, it sounds like you are not using the correct URL to connect to the Information Store (Opal). When you start the Opal server, the URL you must use is displayed in the console.

For example:
 # [opal-services-is]    This application is configured for access on http://hostname/opal

Thanks,
Matt
