### ISSUE TITLE
Audit Log: Is log...() method Necessary?

### ISSUE THREAD

**Issue by GmondLau** [IBM-i2/Analyze#52]
Hi,

I am trying to implement the Audit Log function and have one question.

After enable the is....AuditEnabled(), is it necessary to use the companion log...() method the handle the log? Or the logDefault() already will receive the is....AuditEnabled() log if the companion log...() method is not overridden?

Thanks,
G-mond

**Comment by TonyJon** [comment]
Hi
If you look at the documentation for the IAuditLogger either on GitHub here: 

https://ibm-i2.github.io/Analyze/docs/com/i2group/disco/audit/spi/IAuditLogger.html

Or in the downloaded version of the API documentation that was in your Developer Essentials zip you can see that it says:

![image](https://user-images.githubusercontent.com/17141806/67945966-26902780-fbd8-11e9-835f-a7380e35dd50.png)

So as you have guessed you will get logging without the specific overrides. 

The specific overrides are there  to help you have different details logged for different operations   if you want  it to.

If you are using ANBP then only once you have charted the results will you will see details for what has been retrieved.  

I did find an issue with audit logging for the i2 Investigate  front end  a few months ago, where it is not auditing some of the things it should, so you will not see expand or find path auditing and as you never add items to an ANBP chart when using i2 Investigate you will not see returned  results audited either. (We are hoping to improve auditing in this area for Q4).

**Comment by GmondLau** [comment]
Hi Tony,

Thanks for your clarify, I am closing this issue now.

Thanks,
G-mond
