### ISSUE TITLE
Creating custom merge conditions

### ISSUE THREAD

**Issue by martonnovak** [IBM-i2/Analyze#54]
When using manual data load in i2, one can define merge rules. When these conditions are met, the entities are merged together.

Can we define such conditions when loading data with the data loader java program? So for example there is an existing entity in the dataset, and when I'd load a new one with the same name, day of birth, and mother's name, etc. then it would automatically merge these two into the same entity.

**Comment by boalesth** [comment]
Hi Marton,

Not unless you are prepared to do the manually and then assign the same IDs  ( having a staging table   or database to keep track of things)... and even then it would be an overwrite not a merge.

Thanks

Esther

**Comment by martonnovak** [comment]
Thanks!
