### ISSUE TITLE
Audit Log With Query Data Detail

### ISSUE THREAD

**Issue by GmondLau** [IBM-i2/Analyze#55]
Hi,

I have already succeed implemented the "audit logging to file", but I found that the query result only provide the returned entities & links ID. Is it possible to log the user query result with detail, for example, the entities & links properties?

Thanks,
G-mond

**Comment by TonyJon** [comment]
Hi

The data properties  of an entity or link are not available as part of  the audit iRecordRetrievalAuditEvent, as is  detailed here:

https://ibm-i2.github.io/Analyze/docs/com/i2group/disco/audit/IRecordRetrievalAuditEvent.html

What is returned are iRecordInfo's  shown here:

https://ibm-i2.github.io/Analyze/docs/com/i2group/disco/audit/IRecordInfo.html

You can see what this does include, as you have already mentioned in your request, and  the closest you get to actual data with this is the label Information.

If you want more information on the property values for items that were returned you would have to use the origin information provided and look this up yourself in the database.

Cheers

**Comment by GmondLau** [comment]
Hi Tony,

Thanks! I am closing this case now.

Thanks,
G-mond
