### ISSUE TITLE
Load custom entities with special characters

### ISSUE THREAD

**Issue by martonnovak** [IBM-i2/Analyze#57]
We have built a special schema that fits to an already existing one in i2. Though we have some entities with special characters.

In the data load example, we tried to create a new xml that we can load to the system. Corresponding to the schema4.xsd, we transformed the dataToI2analyze.xslt, and created our forementioned custom data.xml. The xslt and schema4.xsd contains special characters, we made the new xsl tags without special characters, so the .xml will not have them.

To clarify: __Person__ in our currently used language is __Személy__ which is coded as __Szem&#233;ly__. If we would create a new type of entity there would be tags like <Szem&#233;ly> and their corresponding ending tags.

ExampleDataLoaderMain.java does not run with the -load parameter with these tags. Due to the error messages, we tried to convert the tags so there would be simple accented characters (in the dataToI2analyze and in schema4). The load now finishes, but on the onyx web interface we couldn't see the newly added entity under the Személy category (shown correctly with the letter __é__).

These characters are being transformed once we run the __GenerateMappingJar__ command. Are there any parameters that we missing so the conversion would not transform our special characters? If not, then is there a workaround to make it work? 

Thanks in advance,
Marton

**Comment by TonyJon** [comment]
Hi Marton

Can you tell me what the difference is between the **é** in your original type name for Person and the simple accented character you replaced it with? Do they have different encodings? 

You say the characters are being transformed when you use generateMappingJar, do they end up as xml encoded strings like &#00E9  or &eacute for example? 

I have seen this when working with Data Load Direct in German and Danish where some characters are replaced, and in Chinese where all ideograms get replaced like that. If this is the case then you need to make your XSLT write out our XML using those transformed values in the tags and it should then match up. 

If you are getting no errors and also not seeing any new data  for your types it is probably that the tag you are using is not matching the one in  the XSD or your XSLT is not finding a match in your incoming XML.

If you have manually altered the XSD then the XSD will no longer match the corresponding compiled class that we also create during the genrateMappingJar operation and put in the same jar file which can also cause a similar issue.

If this is not what you are seeing then  let me know and I will try tomorrow to see if I can replicate your problem and find a solution.

Cheers
Tony

**Comment by martonnovak** [comment]
> You say the characters are being transformed when you use generateMappingJar, do they end up as xml encoded strings like &#00E9 or &eacute for example?

Exactly!

> Can you tell me what the difference is between the é in your original type name for Person and the simple accented character you replaced it with? Do they have different encodings?

Sorry, in my comment it was converted to __é__, but I wrote the html code equivalent of these letters, I'll try to escape them now, and explain it again.

In the original schema that we are transforming with the generateMappingJar, the Person entity is represented as:  **<EntityType DisplayName="Személy"** ... . After the tranformation, in the generated schema4.xsd the type is now shown as:  **<xs:complexType name="Szem\&#233;ly">**... So the **é** has been transformed to the corresponding html numeric code. We used these types with special codes as the tags in the dataToI2Analyze.xslt when defining our templates. This gave us errors

> [Fatal Error] :70:14: Element type "Szem" must be followed by either attribute specifications, ">" or "/>".
ERROR:  'Could not compile stylesheet'

, since it could not process the remaining letters after __Szem__.

Our Person type with first and last name in our small example looks like this in the dataToI2analyze.xslt:

> 	<xsl:template match="Szemely">
>         <Szem\&#233;ly>
>             <xsl:call-template name="itemTemplate" />
>             <Cards>
>                 <Card>
>                     <xsl:call-template name="cardProvenanceTemplate" />
> 					<Szem\&#233;ly_N\&#233;v>
>                         <xsl:apply-templates select="Veznev" />
>                         <xsl:apply-templates select="Keresztnev" />
>                     </Szem\&#233;ly_N\&#233;v>
>             </Cards>
>         </Szem\&#233;ly>
>     </xsl:template>

While the corresponding part of the schema4.xsd:

>   <xs:complexType name="Szem\&#233;ly">
>     <xs:all>
>       <xs:element name="Cards">
>         <xs:complexType>
>           <xs:sequence>
>             <xs:element name="Card" type="Szem\&#233;ly_CardContent" maxOccurs="unbounded"/>
>           </xs:sequence>
>         </xs:complexType>
>       </xs:element>
>       <xs:element name="ItemId" type="xs:string"/>
>       <xs:element name="ItemVersion" type="xs:long"/>
>       <xs:element name="PropertyBags" minOccurs="0">
>         <xs:complexType>
>           <xs:sequence>
>             <xs:element name="PropertyBag" type="PropertyBag" minOccurs="0" maxOccurs="unbounded"/>
>           </xs:sequence>
>         </xs:complexType>
>       </xs:element>
>       <xs:element name="SecurityTagIds" minOccurs="0">
>         <xs:complexType>
>           <xs:sequence>
>             <xs:element name="SecurityTagId" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
>           </xs:sequence>
>         </xs:complexType>
>       </xs:element>
>     </xs:all>
>   </xs:complexType>
> 
>   <xs:complexType name="Szem\&#233;ly_CardContent">
>     <xs:sequence>
>       <xs:element name="CardId" type="xs:string" minOccurs="0"/>
>       <xs:element ref="ns1:CardProvenance" minOccurs="0"/>
>       <xs:element name="Szem\&#233;ly_Egy\&#233;badatok" type="Szem\&#233;ly_Egy\&#233;badatok" minOccurs="0" maxOccurs="unbounded"/>
>       <xs:element name="Szem\&#233;ly_Forr&#225;s" type="Szem\&#233;ly_Forr&#225;s" minOccurs="0" maxOccurs="unbounded"/>
>       <xs:element name="Szem\&#233;ly_N\&#233;v" type="Szem\&#233;ly_N\&#233;v" minOccurs="0" maxOccurs="unbounded"/>
>       <xs:element name="Szem\&#233;ly_St&#225;tusz" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
>       <xs:element name="Szem\&#233;ly_Sz&#252;let\&#233;siadatok" type="Szem\&#233;ly_Sz&#252;let\&#233;siadatok" minOccurs="0" maxOccurs="unbounded"/>
>     </xs:sequence>
>   </xs:complexType>

We tried the following:
- using the original character code, that gave us errors.
- modify just the dataToI2analyze file, using the accented e letters instead of the codes, it obv. didn't work
- modify also the schema4.xsd so it matches with dataToI2analyze, it did not work either: the data loader java program runs fine, the data is missing from onyx although. Did not give us the already existing id error, so I guess it haven't uploaded the entities at all.

> If you have manually altered the XSD then the XSD will no longer match the corresponding compiled class that we also create during the genrateMappingJar operation and put in the same jar file which can also cause a similar issue.

Ok, so I guess that's why our solutions won't work :) . Maybe altering the transformation of the original xml to the schemas could help, so it would not transform the letters __é__ (and other special accented letters) to their codes.

Thanks,
Marton
